name: Deploy Lambda to AWS

on:
  - push
  - workflow_dispatch

env:
  TF_WORKSPACE: default
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
      # 1Ô∏è‚É£ Checkout do reposit√≥rio
      - uses: actions/checkout@v3

      # 2Ô∏è‚É£ Setup Java 17 e cache Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3Ô∏è‚É£ Build do Maven (fat JAR)
      - name: Build fat JAR with Maven
        run: |
          cd app
          mvn clean package -DskipTests
          echo "üì¶ Conte√∫do da pasta target:"
          ls -la target/
          echo "‚û°Ô∏è Fat JAR gerado:"
          ls -la target/lambda-identification-client.jar

      # 4Ô∏è‚É£ Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1

      # 5Ô∏è‚É£ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 6Ô∏è‚É£ Terraform Init
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}

      # 7Ô∏è‚É£ Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
          TF_VAR_lambda_jar_path: app/target/lambda-identification-client.jar

      # 8Ô∏è‚É£ Terraform Apply (apenas em main/master)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
          TF_VAR_lambda_jar_path: app/target/lambda-identification-client.jar
